"""Next.js / React GA4 component scaffolding and layout wiring."""

from __future__ import annotations

import re
import os
from pathlib import Path
from typing import Any, Dict, Literal, Tuple

from ga4_provision_mcp.snippets import render_gtag_snippet

DEFAULT_ENV_VAR = "NEXT_PUBLIC_GA_MEASUREMENT_ID"
COMPONENT_FILENAME = "GoogleAnalytics.tsx"
PLACEHOLDER_IMPORT = "// GA4_IMPORT_GOOGLE_ANALYTICS"
PLACEHOLDER_USAGE = "{/* GA4_GOOGLE_ANALYTICS */}"


def _validate_measurement_id(measurement_id: str) -> str:
    mid = measurement_id.strip()
    if not re.fullmatch(r"G-[A-Z0-9]+", mid):
        raise ValueError(f"Invalid measurement_id format: {mid!r} (expected G-XXXXXXXX)")
    return mid


def render_nextjs_ga4_component(
    measurement_id: str,
    *,
    mode: Literal["env", "inline"] = "env",
    consent_gated: bool = False,
    env_var: str = DEFAULT_ENV_VAR,
    cookie_consent_key: str = "cookie_consent",
    consent_event_name: str = "cookie-consent",
) -> str:
    """
    Return a Next.js client component using next/script.
    mode=env: read measurement id from process.env.NEXT_PUBLIC_* (recommended).
    mode=inline: embed the measurement id literal in the component.
    """
    mid = _validate_measurement_id(measurement_id)
    env_var = env_var.strip() or DEFAULT_ENV_VAR

    if mode == "env":
        id_expr = f"process.env.{env_var}?.trim()"
    else:
        id_expr = f'"{mid}"'

    if not consent_gated:
        return (
            '"use client";\n\n'
            "import Script from \"next/script\";\n\n"
            "/** GA4 via next/script (generated by ga4-provision-mcp). */\n"
            "export function GoogleAnalytics() {\n"
            f"  const measurementId = {id_expr};\n"
            "  if (!measurementId) return null;\n\n"
            "  return (\n"
            "    <>\n"
            "      <Script\n"
            "        src={`https://www.googletagmanager.com/gtag/js?id=${measurementId}`}\n"
            "        strategy=\"afterInteractive\"\n"
            "      />\n"
            "      <Script id=\"ga4-config\" strategy=\"afterInteractive\">\n"
            "        {`\n"
            "          window.dataLayer = window.dataLayer || [];\n"
            "          function gtag(){dataLayer.push(arguments);}\n"
            "          gtag('js', new Date());\n"
            "          gtag('config', '${measurementId}', { anonymize_ip: true });\n"
            "        `}\n"
            "      </Script>\n"
            "    </>\n"
            "  );\n"
            "}\n"
        )

    return (
        '"use client";\n\n'
        "import Script from \"next/script\";\n"
        "import { useEffect, useState } from \"react\";\n\n"
        f"export const COOKIE_CONSENT_KEY = \"{cookie_consent_key}\";\n\n"
        "function readConsent(): \"accepted\" | \"rejected\" | null {\n"
        "  try {\n"
        "    const v = localStorage.getItem(COOKIE_CONSENT_KEY);\n"
        "    if (v === \"accepted\" || v === \"rejected\") return v;\n"
        "  } catch {\n"
        "    /* private mode */\n"
        "  }\n"
        "  return null;\n"
        "}\n\n"
        "/** GA4 loads only after cookie consent (UK GDPR-friendly). */\n"
        "export function GoogleAnalytics() {\n"
        f"  const measurementId = {id_expr};\n"
        "  const [consent, setConsent] = useState<\"accepted\" | \"rejected\" | null>(null);\n\n"
        "  useEffect(() => {\n"
        "    setConsent(readConsent());\n"
        f"    const onConsent = () => setConsent(readConsent());\n"
        f"    window.addEventListener(\"{consent_event_name}\", onConsent);\n"
        "    window.addEventListener(\"storage\", onConsent);\n"
        "    return () => {\n"
        f"      window.removeEventListener(\"{consent_event_name}\", onConsent);\n"
        "      window.removeEventListener(\"storage\", onConsent);\n"
        "    };\n"
        "  }, []);\n\n"
        "  if (!measurementId || consent !== \"accepted\") return null;\n\n"
        "  return (\n"
        "    <>\n"
        "      <Script\n"
        "        src={`https://www.googletagmanager.com/gtag/js?id=${measurementId}`}\n"
        "        strategy=\"afterInteractive\"\n"
        "      />\n"
        "      <Script id=\"ga4-config\" strategy=\"afterInteractive\">\n"
        "        {`\n"
        "          window.dataLayer = window.dataLayer || [];\n"
        "          function gtag(){dataLayer.push(arguments);}\n"
        "          gtag('js', new Date());\n"
        "          gtag('config', '${measurementId}', { anonymize_ip: true });\n"
        "        `}\n"
        "      </Script>\n"
        "    </>\n"
        "  );\n"
        "}\n"
    )


def render_nextjs_env_line(
    measurement_id: str,
    env_var: str = DEFAULT_ENV_VAR,
) -> str:
    mid = _validate_measurement_id(measurement_id)
    var = env_var.strip() or DEFAULT_ENV_VAR
    return f"{var}={mid}\n"


def _default_component_path(layout_path: Path) -> Path:
    """Guess src/components/GoogleAnalytics.tsx relative to app/layout.tsx."""
    app_dir = layout_path.parent
    if app_dir.name == "app":
        root = app_dir.parent
        return root / "components" / COMPONENT_FILENAME
    return layout_path.parent / "components" / COMPONENT_FILENAME


def _import_path_for_layout(layout_path: Path, component_path: Path) -> str:
    """Prefer @/components/ when layout lives under src/app."""
    layout_path = layout_path.resolve()
    component_path = component_path.resolve()
    if (
        layout_path.parent.name == "app"
        and layout_path.parent.parent.name == "src"
        and component_path.parent.name == "components"
    ):
        return "@/components/GoogleAnalytics"
    rel = os.path.relpath(component_path.with_suffix(""), layout_path.parent)
    rel = rel.replace("\\", "/")
    return rel if rel.startswith(".") else f"./{rel}"


def inject_google_analytics_into_layout(
    layout_source: str,
    *,
    import_path: str = "@/components/GoogleAnalytics",
) -> Tuple[str, str]:
    """
    Add GoogleAnalytics import + JSX usage to a Next.js layout.tsx/jsx file.
    Returns (new_source, action).
    """
    if "GoogleAnalytics" in layout_source and "<GoogleAnalytics" in layout_source:
        return layout_source, "unchanged_already_wired"

    updated = layout_source
    action_parts: list[str] = []

    import_line = f'import {{ GoogleAnalytics }} from "{import_path}";'
    has_ga_import = bool(
        re.search(r'import\s+\{\s*GoogleAnalytics\s*\}\s+from\s+[\'"][^\'"]+[\'"];?', updated)
    )
    if not has_ga_import:
        last_import = None
        for match in re.finditer(r'^import .+;$', updated, re.MULTILINE):
            last_import = match
        if last_import:
            pos = last_import.end()
            updated = updated[:pos] + "\n" + import_line + updated[pos:]
            action_parts.append("added_import")
        elif PLACEHOLDER_IMPORT in updated:
            updated = updated.replace(PLACEHOLDER_IMPORT, import_line)
            action_parts.append("replaced_import_placeholder")
        else:
            updated = import_line + "\n" + updated
            action_parts.append("prepended_import")

    usage_line = "        <GoogleAnalytics />"
    if not re.search(r"<GoogleAnalytics(?:\s|/|>)", updated):
        if PLACEHOLDER_USAGE in updated:
            updated = updated.replace(PLACEHOLDER_USAGE, usage_line)
            action_parts.append("replaced_usage_placeholder")
        else:
            body_open = re.search(r"<body[^>]*>", updated, re.IGNORECASE)
            if body_open:
                insert_at = body_open.end()
                updated = updated[:insert_at] + "\n" + usage_line + updated[insert_at:]
                action_parts.append("injected_after_body")
            else:
                return layout_source, "no_body_tag"

    action = "+".join(action_parts) if action_parts else "unchanged"
    return updated, action


def upsert_env_measurement_id(
    env_content: str,
    measurement_id: str,
    env_var: str = DEFAULT_ENV_VAR,
) -> Tuple[str, str]:
    mid = _validate_measurement_id(measurement_id)
    var = env_var.strip() or DEFAULT_ENV_VAR
    pattern = re.compile(rf"^{re.escape(var)}=.*$", re.MULTILINE)
    line = f"{var}={mid}"
    if pattern.search(env_content):
        new_content = pattern.sub(line, env_content)
        return new_content, "updated_env_var"
    sep = "" if not env_content or env_content.endswith("\n") else "\n"
    return env_content + sep + line + "\n", "appended_env_var"


def scaffold_nextjs_ga4(
    web_root: str,
    measurement_id: str,
    *,
    layout_relative: str = "src/app/layout.tsx",
    component_relative: str = "",
    mode: Literal["env", "inline"] = "env",
    consent_gated: bool = False,
    env_file_relative: str = ".env.local",
    dry_run: bool = False,
) -> Dict[str, Any]:
    """
    Write GoogleAnalytics.tsx, patch layout, and set NEXT_PUBLIC_GA_MEASUREMENT_ID in .env.local.
    web_root: Next.js project root (contains package.json).
    """
    root = Path(web_root).expanduser().resolve()
    if not (root / "package.json").is_file():
        raise ValueError(f"Not a Next.js root (no package.json): {root}")

    layout_path = (root / layout_relative).resolve()
    if not layout_path.is_file():
        raise ValueError(f"Layout not found: {layout_path}")

    component_path = (
        (root / component_relative).resolve()
        if component_relative.strip()
        else _default_component_path(layout_path)
    )
    env_path = (root / env_file_relative).resolve()

    component_src = render_nextjs_ga4_component(
        measurement_id,
        mode=mode,
        consent_gated=consent_gated,
    )
    layout_src = layout_path.read_text(encoding="utf-8", errors="replace")
    import_path = _import_path_for_layout(layout_path, component_path)
    new_layout, layout_action = inject_google_analytics_into_layout(
        layout_src, import_path=import_path
    )

    env_action = "skipped_no_env"
    new_env = ""
    if mode == "env":
        old_env = env_path.read_text(encoding="utf-8", errors="replace") if env_path.is_file() else ""
        new_env, env_action = upsert_env_measurement_id(old_env, measurement_id)

    result: Dict[str, Any] = {
        "web_root": str(root),
        "component_path": str(component_path),
        "layout_path": str(layout_path),
        "env_path": str(env_path) if mode == "env" else None,
        "layout_action": layout_action,
        "env_action": env_action,
        "import_path": import_path,
    }

    if dry_run:
        result["dry_run"] = True
        result["would_write_component"] = True
        result["would_write_layout"] = new_layout != layout_src
        result["would_write_env"] = mode == "env" and (
            not env_path.is_file() or new_env != (env_path.read_text(encoding="utf-8", errors="replace") if env_path.is_file() else "")
        )
        return result

    component_path.parent.mkdir(parents=True, exist_ok=True)
    component_path.write_text(component_src, encoding="utf-8")
    if new_layout != layout_src:
        layout_path.write_text(new_layout, encoding="utf-8")
    if mode == "env":
        env_path.write_text(new_env, encoding="utf-8")

    result["written"] = {
        "component": True,
        "layout": new_layout != layout_src,
        "env": mode == "env",
    }
    return result


def render_nextjs_html_export_snippet(measurement_id: str) -> str:
    """For static HTML export layouts, reuse the standard gtag block."""
    return render_gtag_snippet(measurement_id)
